# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthyFood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('disease', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=20)),
                ('cook', models.CharField(max_length=5)),
                ('ingredient', models.CharField(max_length=500)),
                ('img', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=500)),
                ('protien', models.FloatField()),
                ('fat', models.FloatField()),
                ('carbon', models.FloatField()),
                ('totalcal', models.FloatField()),
                ('nation', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
